main_app/urls.py
from django.urls import path, include
from . import views
from .views import ClothingList, ClothingCreate, ClothingDetail, ClothingUpdate, ClothingDelete, SearchResultsView, SearchWeatherView

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search-by-weather/', SearchWeatherView.as_view(), name='search_weather_results'),
    path('clothing/', ClothingList.as_view(), name='clothing_all'),
    path('clothing/add/', ClothingCreate.as_view(), name='clothing_create'),
    path('clothing/<int:clothing_id>/', ClothingDetail.as_view(), name='clothing_detail'),
    path('clothing/<int:clothing_id>/update', ClothingUpdate.as_view(), name='clothing_update'),
    path('clothing/<int:clothing_id>/delete', ClothingDelete.as_view(), name='clothing_delete'),
    path('clothing/<int:clothing_id>/add_photo/', views.add_photo, name='add_photo'),
    path('photo/<int:pk>/delete', views.PhotoDeleteView.as_view(), name='photo-delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

COLORS = (
    ('Pink', 'Pink'),
    ('Red', 'Red'),
    ('Orange', 'Orange'),
    ('Beige', 'Beige'),
    ('Yellow', 'Yellow'),
    ('Green', 'Green'),
    ('Light Blue', 'Light Blue'),
    ('Dark Blue', 'Dark Blue'),
    ('Purple', 'Purple'),
    ('Brown', 'Brown'),
    ('Grey', 'Grey')
    )

TYPE = (
    ('T-Shirt', 'T-Shirt'),
    ('Sweater', 'Sweater'),
    ('Sweatshirt', 'Sweatshirt'),
    ('Jacket', 'Jacket'),
    ('Jeans', 'Jeans'),
    ('Leggings', 'Leggings'), 
    ('Shorts', 'Shorts'),
    ('Dress Pants', 'Dress Pants'),
    ('Dress', 'Dress'),
    ('Skirt', 'Skirt'),
    ('Blouse', 'Blouse'),
    ('Parka', 'Parka'),
    ('Coat', 'Coat'),
    ('Tank Top', 'Tank Top'),
    )

SEASON = (
    ('Spring', 'Spring'),
    ('Summer', 'Summer'),
    ('Fall', 'Fall'),
    ('Winter', 'Winter'),
    )

class Clothing(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=TYPE, default=TYPE[0][0])
    color = models.CharField(max_length=10, choices=COLORS, default=COLORS[0][0])
    season = models.CharField(max_length=10, choices=SEASON, default=SEASON[0][0])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
  
def __str__(self):
    return self.name

    def __str__(self):
        return self.name

class Photo(models.Model):
    url = models.CharField(max_length=200)
    clothing = models.ForeignKey(Clothing, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for clothing_id: {self.clothing_id} @{self.url}"

# Create inspiration class
# class Inspiration(models.Model):
#     url = models.CharField(max_length=200)
#     description = models.TextField(max_length=100)
#     clothing = models.ForeignKey(Clothing, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"Photo for clothing_id: {self.clothing_id} @{self.url}"

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Clothing, Photo
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
import uuid
import boto3
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
import requests
import os
S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'cmc-4'

season_query = ''

class ClothingCreate(LoginRequiredMixin, CreateView):
  model = Clothing
  fields = ['name', 'type', 'color', 'season']
  def form_valid(self, form):
    form.instance.user = self.request.user 
    return super().form_valid(form)
  success_url = reverse_lazy('clothing_all')

def signup(request):
  error_message=""
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('clothing_all')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def home(request):
   # Weather and IP Lookup API
  url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid={}"
  ipApi_key = os.environ['IPAPI_KEY']
  ipApi_url = "https://ipapi.co/json/?key={}"
  ip_data = requests.get(ipApi_url.format(ipApi_key)).json()
  city = ip_data['city']
  api_key = os.environ['OPEN_WEATHER_KEY']
  weather_data = requests.get(url.format(city, api_key)).json()
  icon = weather_data['weather'][0]['icon']
  
  return render(request, 'home.html', {'weather_data': weather_data, 'icon': icon, 'season_query': season_query})

class ClothingList(ListView):
    model = Clothing
    template_name = 'clothing_all'
    
    def get_queryset(self):
      if self.request.user.is_authenticated:
        return Clothing.objects.filter(user=self.request.user)
      else:
        return Clothing.objects.none()

@login_required 
def clothing_user(request):
  clothing = Clothing.objects.filter(user=request.user)
  return render (request, 'main_app/clothing_detail.html', {'clothing_all': clothing_all})

class ClothingDetail(DetailView):
    model = Clothing
    pk_url_kwarg = "clothing_id"

class ClothingUpdate(UpdateView):
    model = Clothing
    fields = ['name', 'type', 'color', 'season']
    pk_url_kwarg = 'clothing_id'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('clothing_all')

class ClothingDelete(DeleteView):
    model = Clothing
    pk_url_kwarg = 'clothing_id'
    success_url = reverse_lazy('clothing_all')

def about(request):
    return render(request, 'about.html')

def add_photo(request,  clothing_id):
# photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
      s3 = boto3.client('s3')
      # need a unique "key" for S3 / needs image file extension too
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      # just in case something goes wrong
      try:
          s3.upload_fileobj(photo_file, BUCKET, key)
          # build the full url string
          url = f"{S3_BASE_URL}{BUCKET}/{key}"
          # we can assign to clothing_id or clothing (if have clothing object)
          photo = Photo(url=url, clothing_id=clothing_id)
          photo.save()
      except:
          print('An error occurred uploading file to S3')
  return redirect('clothing_detail', clothing_id=clothing_id)


@method_decorator(login_required, name='dispatch')
class PhotoDeleteView(DeleteView):
    model = Photo
    fields = ('__all__')
    success_url = reverse_lazy('clothing_all')
    def get_success_url(self):
      return reverse_lazy('clothing_all')


class SearchResultsView(ListView):
    model = Clothing
    template_name = 'search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Clothing.objects.filter(Q(name__icontains=query) | Q(color__icontains=query) | Q(season__icontains=query) | Q(type__icontains=query)
        )
        if self.request.user.is_authenticated:
          return object_list.filter(user=self.request.user)
        else:
          return Clothing.objects.none()

class SearchWeatherView(ListView):
    model = Clothing
    template_name = 'search_weather_results.html'

    def get_queryset(self):
      query = self.request.GET.get('q')
      query = float(query)
      season_query = ''
      if query <= 8:
        season_query = 'Winter'
      elif query >= 9 and query <= 13:
        season_query = 'Fall'
      elif query >= 14 and query <= 19:
        season_query = 'Spring'
      elif query >= 20:
        season_query = 'Summer'

      object_list = Clothing.objects.filter(
        Q(season__icontains=season_query)
        )
      if self.request.user.is_authenticated:
        return object_list.filter(user=self.request.user)
      else:
        return Clothing.objects.none()

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="about-headline">
<h1>About Compliment My Clothes</h1>
<hr />
<p>Compliment My Clothes (CMC) is here to help you with concerns and challenges when it comes to dressing. From colour coordination to specifically matching tops, bottoms, or outfits together, dressing consultations are on the rise. Use the app to help you with colour coordination and style suggestions. You can even use the built-in weather widget and clothing search to make sure that you're dressed for the weather. Enjoy yourself!</p>
<p>Made with <span style="color: #e25555;">&#9829;</span> by the design team Hannah and Michelle & the developer team Eric, Jasnoor and Hadi.</p>
</div>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>&nbsp;&nbsp;ComplimentMyClothes&nbsp;&nbsp;</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now "U" %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper light-blue darken-4">
        <a href="/" class="brand-logo">Compliment My Clothes</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}   
              <li><a href="{% url 'clothing_all' %}">View My Wardrobe</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
              <li><a href="{% url 'signup' %}">Sign Up</a></li>
              <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'about' %}">About</a></li>
    {% if user.is_authenticated %}   
        <li><a href="{% url 'clothing_all' %}">View My Wardrobe</a></li>
        <li><a href="{% url 'logout' %}">Log Out</a></li>
    {% else %}
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'login' %}">Log In</a></li>
    {% endif %}
  </ul>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <br>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Compliment My Clothes &nbsp;&nbsp;&nbsp;</div>
  </footer>
  <script defer>
  M.AutoInit();

  var elems = document.querySelectorAll('.carousel');
  var xinstances = M.Carousel.init(elems, {
                  fullWidth: true,
                  indicators: true,
                  numVisible: 3,
                  duration: 500
                });

$(document).ready(function(){
    $('.modal').modal();
  }); 
  </script>
</body>
</html>

main_app/templates/clothing.html
{% extends 'base.html' %}
{% block content %}

<h1>Clothing List</h1>

{% for clothing in Clothing %}
  <a href="{% url 'clothing' clothing.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ clothing.name }}</span>
            <p>Type: {{ clothing.type }}</p>
            <p>Colour: {{ clothing.colour }}</p>
            <p>Season: {{ clothing.season }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<br>

<div class="carousel carousel-slider center">
  <div class="carousel-fixed-item center">
    {% if user.is_authenticated %}   
    <a class="btn waves-effect darken-text-2 modal-trigger home-buttons" href="#modal1"><i class="material-icons left">cloud_queue</i>Weather Based Wardrobe</a>
    <a class="btn waves-effect darken-text-2 home-buttons" href="{% url 'clothing_all' %}"><i class="material-icons left">loyalty</i>View My Wardrobe</a>
{% else %}
    <a class="btn waves-effect white grey-text darken-text-2" href="{% url 'signup' %}"><i class="material-icons left">login</i>Sign Up</a>
    <a class="btn waves-effect white grey-text darken-text-2" href="{% url 'login' %}"><i class="material-icons left">vpn_key</i>Log In</a>
{% endif %}
  </div>
  <div class="carousel-item white-text banner" href="#one!">
    <h2>Welcome to Compliment My Clothes</h2>

    <p class="white-text container">Compliment My Clothes (CMC) is here to help you with concerns and challenges when it comes to dressing. Use this app to help you with colour coordination and style suggestions. You can even use the built-in weather widget and clothing search to make sure that you're dressed for the weather. Enjoy yourself!</p>
  </div>
</div>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <div class="row">
        <div class="col s6">
          <h4>Weather in {{weather_data.name}}</h4>
          <h6>Current Temperature: {{weather_data.main.temp}} &#8451;</h6>
          <h6>Feels Like: {{weather_data.main.feels_like}} &#8451;</h6>
          <img src="http://openweathermap.org/img/w/{{ icon }}.png" alt="Image">
        </div>
        <div class="col s6">
          <div class="center">
            <form action="{% url 'search_weather_results' %}" method="get">
              <div class="weather-wardrobe">
                <button class="btn wave-effect" name="q" value="{{weather_data.main.feels_like}}">View Wardrobe Suggestions</button>
              </div>
            </form>
        </div>
        </div>
    </div>
  </div>

{% endblock %}

main_app/templates/main_app/clothing_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<br>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>

<br><br>
{% endblock %}

main_app/templates/main_app/clothing_detail.html
{% extends 'base.html' %} {% block content %}
<br />

<!-- Clothing Item Info Card w/ Edit and Delete -->
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ clothing.name }}</span> <br />
        <p>Type: {{ clothing.type }}</p>
        <br />
        <p>Color: {{ clothing.color }}</p>
        <br />
        <p>Season: {{ clothing.season }}</p>
        <br />
        <div class="modify">
          <a href="{% url 'clothing_update' object.id %}" class="amber waves-effect waves-yellow btn-small">Update</a>
          <a href="{% url 'clothing_delete' object.id %}" class="red lighten-1 waves-effect waves-red btn-small">Delete</a>
       </div>
      </div>
    </div>

   <!-- Complimentary Colors Card -->
   <div class="card">
    <div class="card-content">
      <span class="card-title">Complimentary Colors</span>
        <div class="card-content card-color">
          <div class="pass">
            {% if object.color == 'Orange' %}
            <div class="fullCircle-green">
            </div>
            <div class="fullCircle-light-blue">
            </div>
            <div class="fullCircle-dark-blue">
            </div>
            <div class="fullCircle-white">
            </div>
            <div class="fullCircle-black">
            </div>
          
          {% elif object.color == 'Yellow' %}
          
            <div class="fullCircle-green">
            </div>
            <div class="fullCircle-dark-blue">
            </div>
            <div class="fullCircle-white">
            </div>
            <div class="fullCircle-black">
            </div>
          
          {% elif object.color == 'Pink' %}
          
          <div class="fullCircle-light-blue">
          </div>
          <div class="fullCircle-dark-blue">
          </div>
          <div class="fullCircle-grey">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Red' %}
          
          <div class="fullCircle-light-blue">
          </div>
          <div class="fullCircle-dark-blue">
          </div>
          <div class="fullCircle-grey">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Beige' %}
          
          <div class="fullCircle-dark-blue">
          </div>
          <div class="fullCircle-purple">
          </div>
          <div class="fullCircle-brown">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Green' %}
          
          <div class="fullCircle-orange">
          </div>
          <div class="fullCircle-purple">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Light Blue' %}
          
          <div class="fullCircle-pink">
          </div>
          <div class="fullCircle-red">
          </div>
          <div class="fullCircle-orange">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Dark Blue' %}

          <div class="fullCircle-pink">
          </div>
          <div class="fullCircle-red">
          </div>
          <div class="fullCircle-yellow">
          </div>
          <div class="fullCircle-grey">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>


          {% elif object.color == 'Purple' %}
          
          <div class="fullCircle-orange">
          </div>
          <div class="fullCircle-grey">
          </div>
          <div class="fullCircle-green">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Brown' %}
          
          <div class="fullCircle-beige">
          </div>
          <div class="fullCircle-white">
          </div>
          <div class="fullCircle-black">
          </div>
          
          {% elif object.color == 'Grey' %}
          
          <div class="fullCircle-pink">
          </div>
          <div class="fullCircle-red">
          </div>
          <div class="fullCircle-dark-blue">
          </div>
          <div class="fullCircle-purple">
          </div>

          {% endif %}
      </div>
    </div>
           </div>
      </div>
    </div>

<!-- Delete a Photo Card -->
<div class="col s6 m6">
  <div class="card medium-12">
    <div class="card-content">
      {% for photo in clothing.photo_set.all %}
      <a href = {% url 'photo-delete' photo.id %} class="waves-effect waves-light btn text-align: right" >x</a>
      <img class="responsive-img" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
      </div>
    </div>
<!-- Upload a Photo Card -->
    <form action="{% url 'add_photo' clothing.id %}" enctype="multipart/form-data" method="POST" class="card">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
      </form>    
     </div>
    </div> 
{% endblock %}

main_app/templates/main_app/clothing_form.html
{% extends 'base.html' %}
{% block content %}
<br>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
<br><br>
{% endblock %}

main_app/templates/main_app/clothing_list.html
{% extends 'base.html' %}
{% block content %}
<br>
<form action="{% url 'search_results' %}" method="get">
  <div>
    <input style="display: inline-block" name="q" type="search" placeholder="Search...">
  </div>
</form>
<br>
<div class="add-item">
<a href="/clothing/add" class="waves-effect waves-light btn-large red"><i class="material-icons right">add</i>add item</a>
</div>

<br>

  <div class="row">
  {% for clothing in object_list reversed %}
    <div class="col s6 m6 l4">
      <a href="/clothing/{{ clothing.id }}">
      <div class="card" style="height: 400px;">
      <div class="card-image">
        {% for photo in clothing.photo_set.all %}
      <img style="height: 250px; width: auto;" class="responsive-img" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel teal-text center-align" style="height: 250px; width: auto;">No Photo Uploaded</div>
      {% endfor %}
    </div>
    <div class="card-content">
      <h6>{{clothing.name}}</h6>
      <p>Worn in {{ clothing.season }}</p>
    </div>
      </div>
    </a>
    </div>
  {% endfor %}
  </div>

{% endblock %}

main_app/templates/main_app/clothing_update_form.html
{% extends 'base.html' %}
{% block content %}
<br>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

    <br>
    <br>
{% endblock %}

main_app/templates/main_app/photo_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Delete Photo #{{photo.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ photo.id }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/search_results.html
{% extends 'base.html' %}
{% block content %}

<h1>Search Results</h1>

<div class="row">
  {% for clothing in object_list %}
    <div class="col s6 m6 l4">
      <a href="/clothing/{{ clothing.id }}">
      <div class="card" style="height: 400px;">
      <div class="card-image">
        {% for photo in clothing.photo_set.all %}
      <img style="height: 250px; width: auto;" class="responsive-img" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
    </div>
    <div class="card-content">
      <h6>{{clothing.name}}</h6>
      <p>Worn in {{ clothing.season }}</p>
    </div>
      </div>
    </a>
    </div>
  {% endfor %}
  </div>

{% endblock %}

main_app/templates/search_weather_results.html
{% extends 'base.html' %}
{% block content %}

<h1>Based On Weather</h1>

<div class="row">
  {% for clothing in object_list %}
    <div class="col s6 m6 l4">
      <a href="/clothing/{{ clothing.id }}">
      <div class="card" style="height: 400px;">
      <div class="card-image">
        {% for photo in clothing.photo_set.all %}
      <img style="height: 250px; width: auto;" class="responsive-img" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
    </div>
    <div class="card-content">
      <h6>{{clothing.name}}</h6>
      <p>Worn in {{ clothing.season }}</p>
    </div>
      </div>
    </a>
    </div>
  {% endfor %}
  </div>

{% endblock %}